### ISSUE TITLE
Issues With Declarative Backend Storage Using Git

### ISSUE THREAD

**Issue by sylwang** [flipt-io/flipt-server-sdks#158]
Hi again!

Hopefully this is a proper place to put these questions. We ended up deciding to use Flipt's server side SDKs due to concerns with enabling CGO in our codebase...

1. While trying to deploy the Flipt server, we realized that there isn't a way to specify a file path in the configuration for using Git as the declarative backend storage. Since we have different environments (i.e., staging, production, etc.), we want to deploy an independent instance of Flipt server in each environment. We're aware that we could use "namespaces" in Flipt to handle this data isolation, but we want to take the approach of creating one configuration file for each environment under a directory. 

We considered the possibility to use `.flipt.yml` as mentioned [here](https://www.flipt.io/docs/configuration/storage#locating-flag-state). Since the Flipt servers in different environments share the same Gitlab repository and will refer to the same `.flipt.yml`, this approach would not work...

**And thus the need to specify a file path, indicating where Flipt server should find the FF configuration file. Is there a way to do this?**

2. Another question that came up is that, we're not sure whether there is still a need to configure a relational database. We plan to deploy Flipt in k8s, and based on Flipt's documentation, it seems that configuring a relational database (i.e., PostgreSQL) would help with synchronizing Flipt data among all the replicas, so the configuration each replica gets is the same. However, using Git would turn on the READ ONLY mode. I noticed that only UI was in READ ONLY mode, but I could still use Flipt APIs to create flags. 

**Our goal is to be able to synchronize among all the replicas in k8s, would configuring a relational database be the correct thing to do?**

3. As a result of using Git, I noticed that the slack integration didn't seem to work, and here is my understanding... since the UI was in read-only mode, and Gitlab was used as the single source of truth, we modified `features.yml` to change FF configurations. We want to prevent using any WRITE APIs, such as creating a flag, creating a rollout, etc., because we want to guard all the configuration changes using Gitlab and have other developers approve any change.

![image](https://github.com/flipt-io/flipt-server-sdks/assets/139922338/1ae765ef-bfde-411d-82d5-d0f69a3215cd)

I could see from the UI that the `Created` and `Updated` timestamps were always the same. I tested this with Slack and the Flipt server didn't seem to detect any changes coming from the `features.yml` configuration file. I believe that currently the way how this is set up in Flipt is that, changes can only be detected through the backend APIs (i.e., updating rollout of a flag using API). 

**Is there a way for Slack integration to work with Git and detect changes in `features.yml`?**

Thank you for your help!

**Comment by GeorgeMac** [comment]
Hey @sylwang Great write up, thanks for all the questions!

1. For this specific case you listed, there is not a way (yet)

That said, we could easily add that and get that in pretty quickly I imagine.
This is something I wondered if anyone would ultimately want.
I had imagined that organizing environments across different directories could become a popular approach.

Flipt has the concept of the `.flipt.yml` index file:
https://www.flipt.io/docs/configuration/storage#locating-flag-state
However, this is defined in the repository, and it seems like you want to run multiple instances of Flipt, each pointing at the same repository but different files or directories to represent each environment?

How about if we added a `directory` key to the `git` section of the configuration?
Then we will do the process we do today (look for a `.flipt.yml` in there or fallback to default search strategy).
However, we would scope it to the `directory` field you supply there?

This way you could run Flipt multiple times for different envs using this key.
Putting the different state for each env in each directory?

Quick aside: You can already use branches in Git for different envs, if that interests you.

2. If you can write flag state with these backends enabled, then this sounds like we haven't properly defended against this at the API level

With the declarative backends, the database is primarily kept around to support the authentication methods.
The DB is used to store e.g. session cookie state or static tokens.
You're right that if you don't depend on these, the database should not be required.
I suspect if you're successfully write flag state, that it is putting it in sqlite, but not exposing that via the API.

Would you mind opening that up as its own issue on [Flipt repo](https://github.com/flipt-io/flipt) proper for what you observed there?

3. Sorry that is expected, this needs to be better documented

The Slack integration is based off the audit logging feature, which taps off the write API.
With the declarative backends, we have no way to know e.g. when a flag is specifically created at the source of truth (yet).
This is why the timestamps are always the same.

For now, we kind of expect this kind of introspection to be pushed onto your VCS (Gitlab / GitHub etc).

That said though! If this kind of feature interests you with with the declarative backends, we have some prototypes we've played with to address this. They're not yet useable and we had imagined this kind of feature would be a part of our cloud offering, as they require integrating with e.g. GitHub or GitLabs event streams to build the more accurate timeline and produce events accordingly as state changes on the Git repo server side. This is something we imagine building as a managed app. Would that interest you?

**Comment by sylwang** [comment]
Hi @GeorgeMac, thank you for your quick response!

1. 

> This way you could run Flipt multiple times for different envs using this key.
> Putting the different state for each env in each directory?
This would be something we want. Adding a `directory` field for `Git` in the Flipt configuration would be great. Could you please add this option?

2. And yes, I can open up an independent issue on the Flipt repo and bring it up there.

3. That makes sense that this would be something that needs to be supported in a managed app.

**Comment by GeorgeMac** [comment]
I just opened a PR for adding `directory` to the `git` storage backed ☝️

**Comment by GeorgeMac** [comment]
Hey @sylwang `v1.40.0` just landed with the `directory` configuration property on the storage `git` configuration 👍
