### ISSUE TITLE
.net/c# sdk for OpenFeature

### ISSUE THREAD

**Issue by n2p5** [flipt-io/flipt-server-sdks#177]
### Language

.net/c#

### Willing to Implement

- [X] I'm willing to help implement the Flipt Server SDK in this language if it's accepted. 🙌

### Willing to Review

- [X] I'm willing to review contributions to the Flipt Server SDK in this language if it's accepted.

### Additional Notes

Hi! 

We're looking to implement OpenFeature for a javascript and .net app we have in-house. We'd love to use flipt as our feature backend, but while OpenFeature supports .net, flipt currently does not. We'd love to contribute to help this project, if possible.

**Comment by markphelps** [comment]
Would love help with a c# client!! We are pretty inexperienced with c# so would love someone who knows it better to get the ball rolling.

**Comment by markphelps** [comment]
C# SDK https://www.nuget.org/packages/Flipt/

Now just need to wrap it in OpenFeature SDK

**Comment by markphelps** [comment]
Done! https://github.com/open-feature/dotnet-sdk-contrib/tree/main/src/OpenFeature.Contrib.Providers.Flipt
