### ISSUE TITLE
.net SDK please

### ISSUE THREAD

**Issue by john-need** [flipt-io/flipt-server-sdks#227]
### Language

.net c#

### Willing to Implement

- [ ] I'm willing to help implement the Flipt Server SDK in this language if it's accepted. 🙌

### Willing to Review

- [X] I'm willing to review contributions to the Flipt Server SDK in this language if it's accepted.

**Comment by erka** [comment]
related #86

**Comment by markphelps** [comment]
Published here: https://www.nuget.org/packages/Flipt/ 🎉
