### ISSUE TITLE
[FLI-783] C# Server Side SDK

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt-server-sdks#86]
### Language

C#

### Willing to Implement

- [ ] I'm willing to help implement the Flipt Server SDK in this language if it's accepted. 🙌

### Willing to Review

- [ ] I'm willing to review contributions to the Flipt Server SDK in this language if it's accepted.

### Additional Notes

Re: https://github.com/flipt-io/flipt/discussions/2208

<sub>[FLI-783](https://linear.app/flipt/issue/FLI-783/c-server-side-sdk)</sub>

**Comment by mrjavaguy** [comment]
https://github.com/mrjavaguy/flipt-rest-dotnet/tree/main is an example rest of the openapi, is this what you are after? It used a code generator.
I am also consider writing a dotnet provider for OpenFeature

**Comment by markphelps** [comment]
Hey @mrjavaguy ! Thanks for looking at this! We're totally down for using generated code as long as its idiomatic. Ive only done a bit of C# so would def want to lean on your experience here.

Also, our current Server Side SDKs only expose the Evaluation APIs and (ideally) [ListFlags](https://github.com/flipt-io/flipt-server-sdks/issues/131). Would it be possible to have the generator only generate those methods to keep it consistent with the other languages?

A user in Discord mentioned they were working on a C# OpenFeature SDK as well (unless that was you ;) ) Let me try and find that thread

**Comment by markphelps** [comment]
Found it! https://discord.com/channels/960634591000014878/960697263150227510/1206996127870623744

**Comment by vgwizardx** [comment]
@markphelps So you are looking for Evaluation Api and ListFlag. Are there any other requirements you would like for the C# SDK? I think I'll take a stab at it.

**Comment by markphelps** [comment]
Thanks @vgwizardx !! That would be very much appreciated!

Yes I think the main REST endpoints we need supported are:

- [ListFlags](https://docs.flipt.io/reference/flags/list-flags)
- [BooleanEvaluation](https://docs.flipt.io/reference/evaluation/boolean-evaluation)
- [VariantEvaluation](https://docs.flipt.io/reference/evaluation/variant-evaluation)
- [BatchEvaluation](https://docs.flipt.io/reference/evaluation/batch-evaluation)

With support for authentication: https://docs.flipt.io/reference/overview#authentication

**Comment by vgwizardx** [comment]
@markphelps Hey, I was wondering how ListFlags is used. I'm only asking because I can't really think of a situation where a service using the flags would want to list all the flags. Wouldn't you just use the UI?

**Comment by markphelps** [comment]
@vgwizardx yeah i see your point, and that's what we initially thought as well. we did have one or two users request `ListFlags` in some of our other SDKs so we thought it would be good for parity. However we can also add that later if it's required specifically for this C# SDK.

Happy to just have the evaluation calls implemented for now!

**Comment by vgwizardx** [comment]
@markphelps Cool, I'm working on auth now, and then I will take some time to test it all out.

**Comment by markphelps** [comment]
@vgwizardx awesome! lmk if I can help with anything

**Comment by vgwizardx** [comment]
@markphelps I got super busy. But wanted to share what I have so far. I haven't had a change to test this and might not until next week. But here is what I got so far. https://github.com/vgwizardx/flipt-server-sdks/tree/CSharp-Sdk

**Comment by markphelps** [comment]
This is looking great @vgwizardx !! thank you! do you want to open it up as a PR and we can give it a proper review?

**Comment by vgwizardx** [comment]
@markphelps Yeah, I can do that today. Since I have yet to have a chance to test it and will be busy (My daughter graduated high school this year). So that can help if someone else can give it a try and make sure it is working properly.

**Comment by markphelps** [comment]
> @markphelps Yeah, I can do that today. Since I have yet to have a chance to test it and will be busy (My daughter graduated high school this year). So that can help if someone else can give it a try and make sure it is working properly.

Sounds great. thanks @vgwizardx ! and congrats to your daughter!! 🎓

**Comment by vgwizardx** [comment]
@markphelps don't forget to close this.

**Comment by markphelps** [comment]
Yup, just waiting until we setup CD to push to nuget and will close. Thanks @vgwizardx !

**Comment by markphelps** [comment]
@vgwizardx Im working on getting this SDK released to Nuget and I have a naming question for you (or others familiar with .NET/C# ecosystem)

Should we call this SDK `flipt-dotnet` or `flipt-csharp`? Is there a common idiom for naming? 

I ask because we have an existing gRPC SDK that we named [flipt-grpc-dotnet](https://github.com/flipt-io/flipt-grpc-dotnet/), so i'd prefer to stick with `dotnet` if it makes sense.

**Comment by markphelps** [comment]
Actually.. nevermind it seems we just called it Flipt.grpc

````
dotnet add package Flipt.gRPC --version 0.x.x
```

so I'll just call this `Flipt`

**Comment by vgwizardx** [comment]
@markphelps Yeah, I would just call it Flipt. Another good thing to do is to start with version 0.0.1 (if we are saying alfpha) or 8.0.0 and let the first number match the .net version.

**Comment by markphelps** [comment]
Published here: https://www.nuget.org/packages/Flipt/

Thanks for all your help @vgwizardx !! It really means a lot!

**Comment by vgwizardx** [comment]
I'm happy to help. I will be using this sometime soon, so I will send PRs if I find any improvements.
